In [2]:
import numpy as np

In [3]:
array_1 = np.array([1, 5, 6, 7])
print(array_1)

[1 5 6 7]


In [4]:
array_2 = np.array([7, 2, 4, 1])
print(array_2)

[7 2 4 1]


In [26]:
#Lens of arrays

print(array_1.shape)
print(array_2.shape)

(4,)
(4,)


In [6]:
print(array_1.dtype)

int64


In [7]:
print(array_1 + 2)

[3 7 8 9]


In [8]:
print(array_2 * 2)

[14  4  8  2]


In [9]:
print(array_1 + array_2)

[ 8  7 10  8]


In [11]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print(np.ones((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# We can create arrays using arange function Example: We need from 0 to 10 numbers that can divide to 2

print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [25]:
# Random floats
print(np.random.rand(5))
print(np.random.rand(5, 2))

[0.46081052 0.25940515 0.22567438 0.98015096 0.05192986]
[[0.9923439  0.3056096 ]
 [0.55892707 0.66657597]
 [0.88361137 0.50418341]
 [0.85630183 0.98918249]
 [0.39095661 0.14404821]]


In [23]:
# Random integer
print(np.random.randint(1, 10))
print(np.random.randint(1, 10, 5))

5
[5 1 9 7 6]


In [28]:
# Indexing array

print(array_1[0])
print(array_1[1:2])
print(array_1[-1])

1
[5]
7


In [44]:
# Exercise

array = np.random.randint(1, 10, 5)
print(array)
print('\n')
array = array * 3
print("Multiply array to 3 number = ", array)
print('\n')
print("Even values ", array[array%2==0])

[1 4 3 3 2]


Multiply array to 3 number =  [ 3 12  9  9  6]


Even values  [12  6]
